### ISSUE TITLE
Problem reaching the sitemap.xml file in a build

### ISSUE THREAD

**Issue by jenseo** [tlaundal/sveltekit-static-sitemap#8]
Hey there,
maybe I'm really stupid here but I'm quite new to Sveltekit and has struggled with getting this plugin to work on a Netlify deploy. It get's added correctly to the` /build` folder, but when visiting `mysite.com/sitemap.xml` when serving the build, I get a 404 and I interpret it like Sveltekit expects a route, but nothing found.

I was under the impression that Sveltekit would interpret it as a static asset? I'm using the Netlify adapter, since that's where we deploy our site.

Do I need to exclude the sitemap from the routes somehow?

I've seen some other solutions online where people create their own loader and custom build function for the sitemap which I could do of course, but I was under the impression this was not needed for this plugin? Or how are people actually being able to "visit" their sitemap without Sveltekit interfering and trying to render a route there?

Thanks!

// Jens.

**Comment by jenseo** [comment]
I have also tried with adapter-static btw, but with the same result unfortunately :(

**Comment by jenseo** [comment]
Looking a bit closer, the file does not seem to be added to the .svelte-kit folder in the root, which seems to be the case with the other static assets. Not sure if this is why things go wrong perhaps?

**Comment by tlaundal** [comment]
Hi there,

The sitemap is treated more like a pre-rendered page than like a static asset. When running `npm run build`, the `sitemap.xml` file should be placed next to your other prerendered pages. For Netlify, this should indeed be `build/`.

The sitemap will not be generated in development mode (`npm run dev`), and this is also the reason it doesn't show up anywhere in `.svelte-kit`. 

SvelteKit shouldn't need to be configured to ignore the sitemap in any way. In most deployment environments, the server will check if the file exists as a static asset or a prerendered route first, and only if this is not the case, the SvelteKit server will be invoked. Sadly this doesn't seem to be the case for the preview server, so the sitemap will not show up when using `npm run preview`.

I've never used Netlify before, but I deployed the demo app (with Sverdle and stuff) with this adapter wrapper just now and it seemed to work fine. You can see the sitemap here: https://main--earnest-boba-8e7c70.netlify.app/sitemap.xml

The static adapter also worked well for me.

Could you show the relevant parts of your `svelte.config.js` file please?
When you are on the static adapter and run `npm run build`, does the `sitemap.xml` file show up in the `build/` directory, are there any html files there?
Is this also the case for the netlify adapter?
If you upload the build directory to [Netlify Drop](https://app.netlify.com/drop/) after running `npm run build` with the netlify adapter, can you then access the sitemap at `/sitemap.xml`?

**Comment by dit7ya** [comment]
@tlaundal Slightly related question - in the sitemap URL above, this is what the url look like.

```
<url>
<loc>http://sveltekit-prerender/</loc>
<lastmod>2023-05-03T08:34:12.956Z</lastmod>
<changefreq>monthly</changefreq>
<priority>0.5</priority>
</url>
```

I think the `http://sveltekit-prerender` is simply wrong?

**Comment by tlaundal** [comment]
> I think the `http://sveltekit-prerender` is simply wrong?

`sveltekit-prerender` is the hostname Sveltekit uses during pre-rendering unless you configure it. I should probably add this to the README to it's easy to figure out how to configure it, but you can set it with the following field in the SvelteKit config: `kit.prerender.origin`.

**Comment by tlaundal** [comment]
Closing due to no update from issue creator.
