### ISSUE TITLE
How to generate xhtml:link with hreflang attribute

### ISSUE THREAD

**Issue by artem-ibragimov** [tlaundal/sveltekit-static-sitemap#9]
```html
<url>
<loc>https://example.com</loc>
<xhtml:link rel="alternate" hreflang="en" href="https://example.com"/>
<xhtml:link rel="alternate" hreflang="de" href="https://example.com/de"/>
<xhtml:link rel="alternate" hreflang="fr" href="https://example.com/fr"/>
</url>
```
I tried to generate a sitemap for multi lang site, but I have not found such a param in the docs

**Comment by tlaundal** [comment]
This is not currently implemented, so we can keep this issue open as a
feature request.

It should be quite simple to implement, but I probably won’t have the time
to sit down with this for quite a while. PRs are welcome!
